#!/usr/bin/env bash

# D E F A U L T S

sketchybar -m --bar                           \
position=top                                  \
height=28                                     \
color="0xFF000000"                            \
display=all                                   \
--default                                     \
icon.font="SFMono Nerd Font:Bold:15.0"    \
label.font="SFMono Nerd Font:Italic:15.0" \
associated_display=1                       
