#!/usr/bin/env bash

#TODO: File issue about why 24 background height on modal indicator works but 25 doesn't

# I N I T 
  # Custom Events
    sh ~/.config/sketchybar/custom_events
  # Defaults
    sh ~/.config/sketchybar/defaults

# L E F T
  # Modal Indicator
    sh ~/.config/sketchybar/modal
  # Spaces
    sh ~/.config/sketchybar/spaces
  # Window Title
    sh ~/.config/sketchybar/window_title
  # Stack Indicator
    sh ~/.config/sketchybar/stack_indicator

# R I G H T
    # sketchybar --add item sound right     \
    #            --set sound                \
    #            update_freq=3              \
    #            icon.color=0xffd08770      \
    #            script="$PLUGINS/sound.sh"
  # Battery
    sh ~/.config/sketchybar/battery
  # Date & Clock
    sh ~/.config/sketchybar/date_time
  # CMus  
    sh ~/.config/sketchybar/cmus
  # Investments
    # sh ~/.config/sketchybar/investments

# U P D A T E  B A R
  sketchybar --update

# F I N I S H 
echo "Sketchybar Loaded..."
